### ISSUE TITLE
DynamicFactorMQ is not working

### ISSUE THREAD

**Issue by msh855** [ChadFulton/tsa-notebooks#44]
I am running [this example](https://www.chadfulton.com/topics/statespace_large_dynamic_factor_models.html) 

In the past I had no problems replicating tis example. Now it seems has something changed and I get the following errors when I  try to create the DFM object: 

```

# Construct the dynamic factor model
model = sm.tsa.DynamicFactorMQ(
    endog_m, endog_quarterly=endog_q,
    factors=factors, factor_orders=factor_orders,
    factor_multiplicities=factor_multiplicities)


```
```

Traceback (most recent call last):
  File "/Users/safishajjouz/opt/anaconda3/envs/myport_management_env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-55-40928c00cd95>", line 2, in <module>
    model = sm.tsa.DynamicFactorMQ(
  File "/Users/safishajjouz/opt/anaconda3/envs/myport_management_env/lib/python3.8/site-packages/statsmodels/tsa/statespace/dynamic_factor_mq.py", line 1320, in __init__
    s = self._s = DynamicFactorMQStates(
  File "/Users/safishajjouz/opt/anaconda3/envs/myport_management_env/lib/python3.8/site-packages/statsmodels/tsa/statespace/dynamic_factor_mq.py", line 443, in __init__
    self.factor_block_orders.append(default_block_orders))
  File "/Users/safishajjouz/opt/anaconda3/envs/myport_management_env/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'append'
```

**Comment by efhart4** [comment]
Hi there, I modified a file within the package to remove the append function.

This file:
python3.12/site-packages/statsmodels/tsa/statespace/dynamic_factor_mq.py

And replaced:
self.factor_block_orders.append(default_block_orders))

with this:
self.factor_block_orders = pd.concat([self.factor_block_orders, default_block_orders])
